### ISSUE TITLE
`core-webpack-tools` fails to build with webpack 5.99.0

### ISSUE THREAD

**Issue by paulius-valiunas** [iTwin/itwinjs-core#7993]
`FrontendDefaultsPlugin` seems to be expecting the wrong parameters in a callback. Originally the callback was defined as a generic `Function` type in webpack type declarations, but that was eventually fixed in https://github.com/webpack/webpack/commit/70bdb248e459fb572f1b7f1732b30449e9f6e771#diff-a150fb53afee945f23f3fe7c176007111f3ba81bb0d188af4077d4a0fc4caa37R11059. Now the plugin fails to build if latest version of webpack is installed. This is not noticeable since it's rarely built without the pnpm lock and npmrc files in this repository, but it indicates that the plugin might not work as expected at runtime. It also prevents `core-webpack-tools` from being built inside a cospace.

<details><summary>Build log (click to expand)</summary>
<p>
```
 src/plugins/FrontendDefaultsPlugin.ts:40:7 - error TS2322: Type '(value: any, options: Configuration) => any' is not assignable to type 'string | ((context?: any) => string) | undefined'.
│   Type '(value: any, options: Configuration) => any' is not assignable to type '(context?: any) => string'.
│     Target signature provides too few arguments. Expected 2 or more, but got 1.
│ 
│ 40       compiler.options.output.devtoolModuleFilenameTemplate = (
│          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
│ 
│ 
│ Found 1 error in src/plugins/FrontendDefaultsPlugin.ts:40
```
</p>
</details>

**Comment by aruniverse** [comment]
We removed the package as of 5.0. As we are no longer supporting this, we will close this. If this is needed for 4.x, we can re-open

**Comment by paulius-valiunas** [comment]
Aren't we supposed to support 4.x for a year after the release?

**Comment by aruniverse** [comment]
If someone on 4.x asks for this, we can look into it. However, our recommendation moving forward will be to use tools like Vite
