### PR TITLE
Fix test apps

### PR DESCRIPTION
**Pull request by pmconne**
React to accumulated compilation errors in display-test-app and display-performance-test-app caused by #7683.
We need to fix that issue to prevent new compilation errors from being introduced.

### CODE REVIEW

**Review by markschlosseratbentley — APPROVED** [review]

**Review by bbastings — APPROVED** [review]

File: test-apps/display-test-app/src/frontend/OutputShadersTool.ts [hunk 1]
```diff
@@ -2,8 +2,9 @@
 * Copyright (c) Bentley Systems, Incorporated. All rights reserved.
 * See LICENSE.md in the project root for license terms and full copyright notice.
 *--------------------------------------------------------------------------------------------*/
-import { DebugShaderFile, IModelApp, NotifyMessageDetails, OutputMessagePriority, Tool } from "@itwin/core-frontend";
+import { IModelApp, NotifyMessageDetails, OutputMessagePriority, Tool } from "@itwin/core-frontend";
 import { DtaRpcInterface } from "../common/DtaRpcInterface";
+import { DebugShaderFile } from "@itwin/core-frontend/lib/cjs/internal/render/RenderSystemDebugControl";
```
Comment (aruniverse) [inline test-apps/display-test-app/src/frontend/OutputShadersTool.ts:7]: can you import from esm instead? otherwise you might get dopplegangers at runtime

Comment (aruniverse) [reply test-apps/display-test-app/src/frontend/OutputShadersTool.ts:7]:
```suggestion
import { DebugShaderFile } from "@itwin/core-frontend/lib/esm/internal/render/RenderSystemDebugControl";
```

File: test-apps/display-test-app/src/frontend/TileContentTool.ts [hunk 2]
```diff
@@ -8,6 +8,7 @@ import { PersistentGraphicsRequestProps } from "@itwin/core-common";
 import {
   ImdlReader, IModelApp, IModelConnection, Tool,
 } from "@itwin/core-frontend";
+import { IModelTileTree } from "@itwin/core-frontend/lib/cjs/internal/tile/IModelTileTree";
```
Comment (aruniverse) [inline test-apps/display-test-app/src/frontend/TileContentTool.ts:11]:
```suggestion
import { IModelTileTree } from "@itwin/core-frontend/lib/esm/internal/tile/IModelTileTree";
```

File: test-apps/display-test-app/src/frontend/TileSizeRecorder.ts [hunk 3]
```diff
@@ -5,7 +5,8 @@
 
 import { assert, Id64String } from "@itwin/core-bentley";
 import { iModelTileTreeIdToString } from "@itwin/core-common";
-import { IModelApp, IModelTileTree, TileAdmin, Tool } from "@itwin/core-frontend";
+import { IModelApp, TileAdmin, Tool } from "@itwin/core-frontend";
+import { IModelTileTree } from "@itwin/core-frontend/lib/cjs/internal/tile/IModelTileTree";
```
Comment (aruniverse) [inline test-apps/display-test-app/src/frontend/TileSizeRecorder.ts:9]:
```suggestion
import { IModelTileTree } from "@itwin/core-frontend/lib/esm/internal/tile/IModelTileTree";
```

**Review by aruniverse — COMMENTED** [review]
in pkg.json can you update the build:frontend command to run `tsc`?

File: test-apps/display-test-app/src/frontend/OutputShadersTool.ts (hunk 1 above)
Comment (pmconne) [reply test-apps/display-test-app/src/frontend/OutputShadersTool.ts:7]: Already tried that. We still need cjs and esm for the test apps?

```
rc/frontend/App.ts:import { ElectronApp, ElectronAppOpts } from "@itwin/core-electron/lib/cjs/ElectronFrontend";
src/frontend/App.ts:import { MobileApp, MobileAppOpts } from "@itwin/core-mobile/lib/cjs/MobileFrontend";
src/frontend/FileOpen.ts:import { ElectronApp } from "@itwin/core-electron/lib/cjs/ElectronFrontend";
src/frontend/OutputShadersTool.ts:import { DebugShaderFile } from "@itwin/core-frontend/lib/cjs/internal/render/RenderSystemDebugControl";
j2 display-test-app: pmc/fix-display-test-app-compilation-errors 14:27:22 ~/c/j2/s/itwinjs/test-apps/display-test-app 0> npm run build:frontend

> display-test-app@1.8.0 build:frontend
> tsc

src/frontend/App.ts:7:46 - error TS2307: Cannot find module '@itwin/core-electron/lib/esm/ElectronFrontend' or its corresponding type declarations.

7 import { ElectronApp, ElectronAppOpts } from "@itwin/core-electron/lib/esm/ElectronFrontend";
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/frontend/FileOpen.ts:7:29 - error TS2307: Cannot find module '@itwin/core-electron/lib/esm/ElectronFrontend' or its corresponding type declarations.

7 import { ElectronApp } from "@itwin/core-electron/lib/esm/ElectronFrontend";
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/frontend/TileContentTool.ts:25:80 - error TS2322: Type 'import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/esm/internal/tile/IModelTileTree").IModelTileTree' is no
  The types of 'decoder.decode' are incompatible between these types.
    Type '(args: import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/esm/internal/tile/ImdlDecoder").ImdlDecodeArgs) => Promise<import("/home/paul/c/j2/s/itwinjs/core/f
      Types of parameters 'args' and 'args' are incompatible.
        Type 'import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/cjs/internal/tile/ImdlDecoder").ImdlDecodeArgs' is not assignable to type 'import("/home/paul/c/j2/s/i
          The types returned by 'system.createTarget(...)' are incompatible between these types.
            Property '[_implementationProhibited]' is missing in type 'import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/cjs/render/RenderTarget").RenderTarget' but required in type 'import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/esm/render/RenderTarget").RenderTarget'.

25       const bytes = await IModelApp.tileAdmin.generateTileContent({ contentId, iModelTree: tree });
                                                                                  ~~~~~~~~~~

  ../../core/frontend/lib/esm/render/RenderTarget.d.ts:37:33
    37     protected abstract readonly [_implementationProhibited]: unknown;
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    '[_implementationProhibited]' is declared here.
  ../../core/frontend/lib/cjs/tile/TileAdmin.d.ts:316:9
    316         iModelTree: IModelTileTree;
                ~~~~~~~~~~
    The expected type comes from property 'iModelTree' which is declared here on type '{ iModelTree: IModelTileTree; contentId: string; request?: { isCanceled: boolean; } | undefined; }'

src/frontend/TileContentTool.ts:29:17 - error TS2741: Property '[_requestSnap]' is missing in type 'import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/esm/IModelConnection").IModelConnection' but required in type 'import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/cjs/IModelConnection").IModelConnection'.

29         stream, iModel, modelId, is3d, containsTransformNodes,
                   ~~~~~~

  ../../core/frontend/lib/cjs/IModelConnection.d.ts:174:5
    174     [_requestSnap](props: SnapRequestProps): Promise<SnapResponseProps>;
            ~~~~~~~~~~~~~~
    '[_requestSnap]' is declared here.
  ../../core/frontend/lib/cjs/tile/ImdlReader.d.ts:32:5
    32     iModel: IModelConnection;
           ~~~~~~
    The expected type comes from property 'iModel' which is declared here on type 'ImdlReaderCreateArgs'

src/frontend/TileContentTool.ts:60:45 - error TS2339: Property 'modelId' does not exist on type 'never'.

60       if (tree && "modelId" in tree && tree.modelId === modelId)
                                               ~~~~~~~

src/frontend/TileSizeRecorder.ts:98:7 - error TS2322: Type '(tile: { iModelTree: IModelTileTree; contentId: string; request?: { isCanceled: boolean; }; }) => Promise<Uint8Array>' is not assignable to type '(tile: { iModelTree: IModelTileTree; contentId: string; request?: { isCanceled: boolean; } | undefined; }) => Promise<Uint8Array>'.
  Types of parameters 'tile' and 'tile' are incompatible.
    Type '{ iModelTree: import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/cjs/internal/tile/IModelTileTree").IModelTileTree; contentId: string; request?: { isCanceled: boolean; } | undefined; }' is not assignable to type '{ iModelTree: import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/esm/internal/tile/IModelTileTree").IModelTileTree; contentId: string; request?: { isCanceled: boolean; } | undefined; }'.
      The types of 'iModelTree.decoder.decode' are incompatible between these types.
        Type '(args: import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/cjs/internal/tile/ImdlDecoder").ImdlDecodeArgs) => Promise<import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/cjs/tile/ImdlReader").ImdlReaderResult>' is not assignable to type '(args: import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/esm/internal/tile/ImdlDecoder").ImdlDecodeArgs) => Promise<import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/esm/tile/ImdlReader").ImdlReaderResult>'.
          Types of parameters 'args' and 'args' are incompatible.
            Type 'import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/esm/internal/tile/ImdlDecoder").ImdlDecodeArgs' is not assignable to type 'import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/cjs/internal/tile/ImdlDecoder").ImdlDecodeArgs'.
              The types returned by 'system.createTarget(...)' are incompatible between these types.
                Property '[_implementationProhibited]' is missing in type 'import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/esm/render/RenderTarget").RenderTarget' but required in type 'import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/cjs/render/RenderTarget").RenderTarget'.

98       IModelApp.tileAdmin.generateTileContent = async (tile: { iModelTree: IModelTileTree, contentId: string, request?: { isCanceled: boolean } }): Promise<Uint8Array> => {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  ../../core/frontend/lib/cjs/render/RenderTarget.d.ts:37:33
    37     protected abstract readonly [_implementationProhibited]: unknown;
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    '[_implementationProhibited]' is declared here.

src/frontend/TileSizeRecorder.ts:99:77 - error TS2345: Argument of type '{ iModelTree: import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/esm/internal/tile/IModelTileTree").IModelTileTree; contentId: string; request?: { isCanceled: boolean; } | undefined; }' is not assignable to parameter of type '{ iModelTree: import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/cjs/internal/tile/IModelTileTree").IModelTileTree; contentId: string; request?: { isCanceled: boolean; } | undefined; }'.
  The types of 'iModelTree.decoder.decode' are incompatible between these types.
    Type '(args: import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/esm/internal/tile/ImdlDecoder").ImdlDecodeArgs) => Promise<import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/esm/tile/ImdlReader").ImdlReaderResult>' is not assignable to type '(args: import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/cjs/internal/tile/ImdlDecoder").ImdlDecodeArgs) => Promise<import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/cjs/tile/ImdlReader").ImdlReaderResult>'.
      Types of parameters 'args' and 'args' are incompatible.
        Type 'import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/cjs/internal/tile/ImdlDecoder").ImdlDecodeArgs' is not assignable to type 'import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/esm/internal/tile/ImdlDecoder").ImdlDecodeArgs'.
          The types returned by 'system.createTarget(...)' are incompatible between these types.
            Property '[_implementationProhibited]' is missing in type 'import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/cjs/render/RenderTarget").RenderTarget' but required in type 'import("/home/paul/c/j2/s/itwinjs/core/frontend/lib/esm/render/RenderTarget").RenderTarget'.

99         const content = await generateTileContent.bind(IModelApp.tileAdmin, tile)();
                                                                               ~~~~

  ../../core/frontend/lib/esm/render/RenderTarget.d.ts:37:33
    37     protected abstract readonly [_implementationProhibited]: unknown;
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    '[_implementationProhibited]' is declared here.


Found 7 errors in 4 files.

Errors  Files
     1  src/frontend/App.ts:7
     1  src/frontend/FileOpen.ts:7
     3  src/frontend/TileContentTool.ts:25
     2  src/frontend/TileSizeRecorder.ts:98
j2 display-test-app: pmc/fix-display-test-app-compilation-errors 14:28:39 ~/c/j2/s/itwinjs/test-apps/display-test-app 0> npm run build
```

File: test-apps/display-test-app/src/frontend/TileContentTool.ts (hunk 2 above)
Comment (pmconne) [reply test-apps/display-test-app/src/frontend/TileContentTool.ts:11]: See other comment.

**Comment by pmconne** [comment]
> in pkg.json can you update the build:frontend command to run `tsc`?

It already does.

**Review by tcobbs-bentley — APPROVED** [review]
I don't understand the cjs/esm stuff, but everything else looks ok to me.

File: test-apps/display-test-app/src/frontend/OutputShadersTool.ts (hunk 1 above)
Comment (aruniverse) [reply test-apps/display-test-app/src/frontend/OutputShadersTool.ts:7]: gah, thats annoying, thanks for sharing. didn't realize it was still pulling cjs of core-frontend. will try to remove this once we have an esm build of core-electron and core-mobile

Comment (aruniverse) [reply test-apps/display-test-app/src/frontend/OutputShadersTool.ts:7]: fyi @hl662
